---

additional-dependency-files:

  - type: bundler-gemfile
    path: Gemfile

  - type: pip-requirements-txt
    path: requirements.txt

ignore-failures:

  python:
    - async-generator
    - backcall
    - cycler
    - entrypoints
    - ipython-genutils
    - jupyter
    - mccabe
    - mistune
    - pexpect
    - pickleshare
    - qtpy
    - send2trash
    - webencodings
    - widgetsnbextension

  ruby:
    - ruby-lint
